Set @NUM :=0;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 0,5;

Set @NUM :=5;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 5,5;

Set @NUM :=10;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 10,5;

Set @NUM :=15;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 15,5;

Set @NUM :=20;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 20,5;

Set @NUM :=25;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 5,5;

Set @NUM :=30;
SELECT @NUM:=@NUM+1 AS `NO`, T.* FROM `MEMBER` T LIMIT 30,5;